steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c','docker login -u juzheng -p $$PASSWORD' ]
    secretEnv: [ 'PASSWORD' ]


  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'juzheng/tw-cn-backend', 'backend/' ]
    timeout: 500s

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c','docker push juzheng/tw-cn-backend']


  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'juzheng/tw-cn-frontend', 'frontend/' ]
    timeout: 500s

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c','docker push juzheng/tw-cn-frontend' ]


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/DOCKER_PASSWORD_SECRET_NAME/versions/1
      env: 'PASSWORD'
