version: '3'
services:
  backend:
    image: 'juzheng/tw-cn-backend'
    expose:
      - 9999
    restart: unless-stopped
  frontend:
    image: 'juzheng/tw-cn-frontend'
    environment:
      - "API_BASE_URL=https://tw-cn.skyju.cc/backend/"
    expose:
      - 80
    restart: unless-stopped
  nginx:
    image: 'nginx:stable-alpine'
    depends_on:
      - backend
      - frontend
    ports:
    - "18080:80"
    restart: unless-stopped
    volumes:
    - "./nginx.conf:/etc/nginx/conf.d/default.conf"
